export const TRANSLATIONS = {
  en: {
    // Subject screen
    chooseSubject: "Choose Your Subject",
    selectSubject: "Select a subject to begin your learning journey",
    class: "Class",
    age: "Age",

    learningGoal: "Your Learning Goal",
    interactiveNotes: "📚 Interactive notes to support your learning",
    smartQuizzes: "🧠 Smart quizzes to strengthen problem-solving skills",
    funGames: "🎮 Fun learning activities",

    practiceTip:
      "Practice regularly to build a strong understanding of concepts.",

    focusAreaBody:
      "Learning this concept well can help improve performance in related topics and assessments.",

    // Onboarding
    letsGetStarted: "Let's Get Started!",
    selectYourClass: "Select Your Class",
    whatsYourName: "What's Your Name?",
    howOldAreYou: "How Old Are You?",
    whyDoYouWantToLearn: "Why Do You Want to Learn?",
    chooseClassHint:
      "Choose your current class level to get personalized content",
    enterYourName: "Enter your name",
    enterYourAge: "Enter your age",
    nameHint:
      "Tell us your name so we can personalize your learning experience",
    ageHint:
      "Knowing your age helps us create age-appropriate content for you",
    reasonHint:
      "Understanding your learning goals helps us personalize content",

    enterReasonPlaceholder:
      "I want to improve my grades, learn new concepts, prepare for exams...",

    back: "Back",
    next: "Next",
    startLearning: "Start Learning!",

        // UI labels
    topicsNotes: "Topics & Notes",
    seeWhatYouveLearnt: "Review Your Learning",
    timeToPlay: "Let's Play",
    topicsForClassPrefix: "Topics for Class ",
    clickAnyTopic:
      "Click any topic to view detailed notes and explanations",
    readNotes: "Read Notes",
    noTopicsAvailableHeading: "No Topics Available",
    noTopicsAvailableBodyPrefix: "Topics for ",
    quickReviewNotes: "Quick Review Notes",
    keyPointsToRemember: "Key Points to Remember",
    quickTip: "💡 Study Tip",
    focusArea: "🎯 Focus Area",
    takePracticeQuiz: "Take Practice Quiz",
    viewRelatedTopics: "View Related Topics",

    // Translation labels
    translateTitle: "Translate",
    originalLang: "Original language",
    targetLang: "Target language",
    enterOriginal: "Enter text in original language",
    enterOriginalPlaceholder: "Type here...",
    translate: "Translate",
    translating: "Translating...",
    translateFailed: "Translation failed",
    clear: "Clear",
    copy: "Copy",
  },
 
mr: {
  chooseSubject: "तुमचा विषय निवडा",
  selectSubject: "तुमचा शिकण्याचा प्रवास सुरू करण्यासाठी एक विषय निवडा",
  class: "इयत्ता",
  age: "वय",
  class: "इयत्ता",
  age: "वय",
  learningGoal: "तुमचे शिकण्याचे उद्दिष्ट",
  interactiveNotes: "📚 परस्परसंवादी नोट्स अभ्यासात मदत करतील",
  smartQuizzes: "🧠 स्मार्ट क्विझ प्रश्न सोडवण्याची क्षमता सुधारतील",
  funGames: "🎮 मजेदार खेळ",

  // UI-wide labels
  topicsNotes: "विषय आणि नोट्स",
  seeWhatYouveLearnt: "तुम्ही काय शिकलात ते पहा",
  timeToPlay: "खेळण्याची वेळ",
  topicsForClassPrefix: "इयत्तेसाठी विषय ",
  clickAnyTopic: "सविस्तर नोट्स आणि स्पष्टीकरण पाहण्यासाठी कोणत्याही विषयावर क्लिक करा",
  readNotes: "नोट्स वाचा",
  noTopicsAvailableHeading: "कोणतेही विषय उपलब्ध नाहीत",
  noTopicsAvailableBodyPrefix: "यासाठी विषय ",
  quickReviewNotes: "जलद पुनरावलोकन नोट्स",
  keyPointsToRemember: "लक्षात ठेवण्यासारखे मुख्य मुद्दे",
  quickTip: "💡 जलद टिप",
  focusArea: "🎯 लक्ष केंद्रित क्षेत्र",
  takePracticeQuiz: "सराव प्रश्नमंजुषा घ्या",
  viewRelatedTopics: "संबंधित विषय पहा",

  // Onboarding
  letsGetStarted: "चला सुरुवात करूया!",
  selectYourClass: "तुमची इयत्ता निवडा",
  whatsYourName: "तुमचे नाव काय आहे?",
  howOldAreYou: "तुमचे वय किती आहे?",
  whyDoYouWantToLearn: "तुम्हाला शिकायचे का आहे?",
  chooseClassHint: "वैयक्तिक सामग्री मिळवण्यासाठी तुमची सध्याची इयत्ता निवडा",
  enterYourName: "तुमचे नाव टाका",
  enterYourAge: "तुमचे वय टाका",
  nameHint: "तुमचा शिकण्याचा अनुभव वैयक्तिक करण्यासाठी आम्हाला तुमचे नाव सांगा",
  ageHint: "तुमचे वय जाणून घेतल्याने आम्हाला तुमच्यासाठी योग्य सामग्री तयार करता येते",
  reasonHint: "तुमचे शिकण्याचे उद्दिष्ट समजल्याने सामग्री वैयक्तिक करता येते",
  enterReasonPlaceholder: "मला माझे गुण सुधारायचे आहेत, नवीन संकल्पना शिकायच्या आहेत, परीक्षेची तयारी करायची आहे...",
  back: "मागे",
  next: "पुढे",
  startLearning: "शिकणे सुरू करा!",

  // translate UI labels
  translateTitle: "भाषांतर",
  originalLang: "मूळ भाषा",
  targetLang: "लक्ष्य भाषा",
  enterOriginal: "मूळ भाषेतील मजकूर प्रविष्ट करा",
  enterOriginalPlaceholder: "इथे टाइप करा...",
  translate: "भाषांतर करा",
  translating: "भाषांतर सुरू आहे...",
  translateFailed: "भाषांतर अयशस्वी झाले",
  clear: "साफ करा",
  copy: "कॉपी करा",
}, 
  
   kn: {
  chooseSubject: "ನಿಮ್ಮ ವಿಷಯವನ್ನು ಆಯ್ಕೆಮಾಡಿ",
  selectSubject: "ನಿಮ್ಮ ಕಲಿಕಾ ಪ್ರಯಾಣವನ್ನು ಪ್ರಾರಂಭಿಸಲು ಒಂದು ವಿಷಯವನ್ನು ಆಯ್ಕೆಮಾಡಿ",
  class: "ತರಗತಿ",
  age: "ವಯಸ್ಸು",
  learningGoal: "ನಿಮ್ಮ ಕಲಿಕಾ ಗುರಿ",
  interactiveNotes: "📚 ಸಂವಾದಾತ್ಮಕ ಟಿಪ್ಪಣಿಗಳು ಅಧ್ಯಯನಕ್ಕೆ ಸಹಾಯ ಮಾಡುತ್ತವೆ",
  smartQuizzes: "🧠 ಸ್ಮಾರ್ಟ್ ಕ್ವಿಜ್‌ಗಳು ಪ್ರಶ್ನೆ ಪರಿಹಾರ ಕೌಶಲ್ಯಗಳನ್ನು ಉತ್ತಮಗೊಳಿಸುತ್ತವೆ",
  funGames: "🎮 ಮನರಂಜನಾತ್ಮಕ ಆಟಗಳು",
    
  // UI-wide labels
  topicsNotes: "ವಿಷಯಗಳು ಮತ್ತು ಟಿಪ್ಪಣಿಗಳು",
  seeWhatYouveLearnt: "ನೀವು ಕಲಿತದ್ದನ್ನು ನೋಡಿ",
  timeToPlay: "ಆಟದ ಸಮಯ",
  topicsForClassPrefix: "ತರಗತಿಗಾಗಿ ವಿಷಯಗಳು ",
  clickAnyTopic: "ವಿವರವಾದ ಟಿಪ್ಪಣಿಗಳು ಮತ್ತು ವಿವರಣೆಗಳನ್ನು ನೋಡಲು ಯಾವುದೇ ವಿಷಯವನ್ನು ಕ್ಲಿಕ್ ಮಾಡಿ",
  readNotes: "ಟಿಪ್ಪಣಿಗಳನ್ನು ಓದಿ",
  noTopicsAvailableHeading: "ಯಾವುದೇ ವಿಷಯಗಳು ಲಭ್ಯವಿಲ್ಲ",
  noTopicsAvailableBodyPrefix: "ವಿಷಯಗಳು ",
  quickReviewNotes: "ತ್ವರಿತ ಮರುಪರಿಶೀಲನೆ ಟಿಪ್ಪಣಿಗಳು",
  keyPointsToRemember: "ನೆನಪಿಡಬೇಕಾದ ಮುಖ್ಯ ಅಂಶಗಳು",
  quickTip: "💡 ತ್ವರಿತ ಸಲಹೆ",
  focusArea: "🎯 ಗಮನದ ಕ್ಷೇತ್ರ",
  takePracticeQuiz: "ಅಭ್ಯಾಸ ಕ್ವಿಜ್ ತೆಗೆದುಕೊಳ್ಳಿ",
  viewRelatedTopics: "ಸಂಬಂಧಿತ ವಿಷಯಗಳನ್ನು ನೋಡಿ",

  // Onboarding
  letsGetStarted: "ಪ್ರಾರಂಭಿಸೋಣ!",
  selectYourClass: "ನಿಮ್ಮ ತರಗತಿಯನ್ನು ಆಯ್ಕೆಮಾಡಿ",
  whatsYourName: "ನಿಮ್ಮ ಹೆಸರು ಏನು?",
  howOldAreYou: "ನಿಮ್ಮ ವಯಸ್ಸು ಎಷ್ಟು?",
  whyDoYouWantToLearn: "ನೀವು ಏಕೆ ಕಲಿಯಲು ಬಯಸುತ್ತೀರಿ?",
  chooseClassHint: "ವೈಯಕ್ತಿಕಗೊಳಿಸಿದ ವಿಷಯವನ್ನು ಪಡೆಯಲು ನಿಮ್ಮ ಪ್ರಸ್ತುತ ತರಗತಿ ಮಟ್ಟವನ್ನು ಆಯ್ಕೆಮಾಡಿ",
  enterYourName: "ನಿಮ್ಮ ಹೆಸರನ್ನು ನಮೂದಿಸಿ",
  enterYourAge: "ನಿಮ್ಮ ವಯಸ್ಸನ್ನು ನಮೂದಿಸಿ",
  nameHint: "ನಿಮ್ಮ ಕಲಿಕೆಯ ಅನುಭವವನ್ನು ವೈಯಕ್ತಿಕಗೊಳಿಸಲು ನಿಮ್ಮ ಹೆಸರನ್ನು ನಮಗೆ ತಿಳಿಸಿ",
  ageHint: "ನಿಮ್ಮ ವಯಸ್ಸನ್ನು ತಿಳಿದುಕೊಳ್ಳುವುದರಿಂದ ನಿಮಗೆ ಸೂಕ್ತವಾದ ವಿಷಯವನ್ನು ರಚಿಸಲು ಸಹಾಯವಾಗುತ್ತದೆ",
  reasonHint: "ನಿಮ್ಮ ಕಲಿಕಾ ಗುರಿಗಳನ್ನು ಅರ್ಥಮಾಡಿಕೊಳ್ಳುವುದರಿಂದ ವಿಷಯವನ್ನು ವೈಯಕ್ತಿಕಗೊಳಿಸಲು ಸಹಾಯವಾಗುತ್ತದೆ",
  enterReasonPlaceholder: "ನಾನು ನನ್ನ ಅಂಕಗಳನ್ನು ಸುಧಾರಿಸಬೇಕು, ಹೊಸ ಪರಿಕಲ್ಪನೆಗಳನ್ನು ಕಲಿಯಬೇಕು, ಪರೀಕ್ಷೆಗೆ ತಯಾರಿ ಮಾಡಿಕೊಳ್ಳಬೇಕು...",
  back: "ಹಿಂದೆ",
  next: "ಮುಂದೆ",
  startLearning: "ಕಲಿಕೆಯನ್ನು ಪ್ರಾರಂಭಿಸಿ!",

  // Translation labels
  translateTitle: "ಅನುವಾದ",
  originalLang: "ಮೂಲ ಭಾಷೆ",
  targetLang: "ಗುರಿ ಭಾಷೆ",
  enterOriginal: "ಮೂಲ ಭಾಷೆಯ ಪಠ್ಯವನ್ನು ನಮೂದಿಸಿ",
  enterOriginalPlaceholder: "ಇಲ್ಲಿ ಟೈಪ್ ಮಾಡಿ...",
  translate: "ಅನುವಾದಿಸಿ",
  translating: "ಅನುವಾದಿಸಲಾಗುತ್ತಿದೆ...",
  translateFailed: "ಅನುವಾದ ವಿಫಲವಾಗಿದೆ",
  clear: "ಅಳಿಸಿ",
  copy: "ನಕಲಿಸಿ",
  },
  ml: {
  "మీ విషయం ఎంచుకోండి",
    selectSubject: "మీ అభ్యాస ప్రయాణాన్ని ప్రారంభించేందుకు విషయాన్ని ఎంచుకోండి",
    class: "తరగతి",
    age: "వయస్సు",
    learningGoal: "మీ అభ్యాస లక్ష్యం",
    interactiveNotes: "📚 ఇంటరాక్టివ్ నోట్స్ చదువులో సహాయపడతాయి",
    smartQuizzes: "🧠 స్మార్ట్ క్విజ్‌లు ప్రశ్నలు పరిష్కరించడాన్ని మెరుగుపరుస్తాయి",
    funGames: "🎮 సరదా ఆటలు",

    topicsNotes: "Topics & Notes",
    seeWhatYouveLearnt: "See What You've Learnt",
    timeToPlay: "Time to Play",
    topicsForClassPrefix: "Topics for Class ",
    clickAnyTopic: "Click on any topic to view detailed notes and explanations",
    readNotes: "Read Notes",
    noTopicsAvailableHeading: "No Topics Available",
    noTopicsAvailableBodyPrefix: "Topics for ",
    quickReviewNotes: "Quick Review Notes",
    keyPointsToRemember: "Key Points to Remember",
    quickTip: "💡 Quick Tip",
    focusArea: "🎯 Focus Area",
    takePracticeQuiz: "Take Practice Quiz",
    viewRelatedTopics: "View Related Topics",

    letsGetStarted: "Let's Get Started!",
    selectYourClass: "Select Your Class",
    whatsYourName: "What's Your Name?",
    howOldAreYou: "How Old Are You?",
    whyDoYouWantToLearn: "Why Do You Want to Learn?",
    chooseClassHint: "Choose your current class level to get personalized content",
    enterYourName: "Enter your name",
    enterYourAge: "Enter your age",
    nameHint: "Tell us your name so we can personalize your learning experience",
    ageHint: "Knowing your age helps us create age-appropriate content for you",
    reasonHint: "Understanding your learning goals helps us personalize content",
    enterReasonPlaceholder:
      "I want to improve my grades, learn new concepts, prepare for exams...",
    back: "Back",
    next: "Next",
    startLearning: "Start Learning!",

    translateTitle: "Translate",
    originalLang: "Original language",
    targetLang: "Target language",
    enterOriginal: "Enter text in original language",
    enterOriginalPlaceholder: "Type here...",
    translate: "Translate",
    translating: "Translating...",
    translateFailed: "Translation failed",
    clear: "Clear",
    copy: "Copy",
  }
};
